apiVersion: skaffold/v2beta17
kind: Config
metadata:
  name: cicd
build:
  artifacts:
  - image: gcr.io/veerahemannthnag/helloworld
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s-deployment.yaml
    - k8s-service.yaml